### ISSUE TITLE
Error when running MutSig2CV_NC

### ISSUE THREAD

**Issue by ChongJenniferZhang** [broadinstitute/getzlab-PCAWG-MutSig2CV_NC#1]
Hi,

I am trying to run Mutsig2CV_NC on my own HCC WGS data with MATLAB v2019a on Windows and MCR on linux, like
"
 MutSig2CV_NC('input/input.fiveCol.maf', 'output', 'run/params/Liver-HCC_alt_prom.params.txt') "
 Then it showed
"
WILL LOAD+RUN.
LOADING DATA
"
But then I encountered  errors said
"
errors when using require_fields (line 9)
Structure is missing required field "num"
Error: demand_fields (line 2)
require_fields(varargin{:});
Error: map_categories_to_65 (line 15)
demand_fields(C,{'num','name'});
Error MutSig2CV_v5_load (line 78)
M.context_and_effect.context65 =
map_categories_to_65(context_and_effect_categs_file); %XXX: make sure this works
Error MutSig2CV_NC (line 96)
[M P] = MutSig2CV_v5_load(args{:}); 
"
in Windows and
" 
Structure is missing required field "num"
Error in demand_fields (line 2)
Error in map_categories_to_65 (line 15)
Error in MutSig2CV_v5_load (line 78)
Error in MutSig2CV_v5_wrapper (line 96)
" in linux.

Could you please tell me how should I avoid such errors? Many thanks.

Best wishes,
Jennifer

**Comment by julianhess** [comment]
Hi Jennifer,

Can you please show me the contents of `ref/c65e15/categs.txt`?  It should look something like this:

```
% head -n5 categs.txt
num	name
1	A in A_A:psg,deg-2
2	A in A_A:psg,deg-1
3	A in A_A:psg,psg
4	A in A_A:psg,deg1
```

Thanks so much,
--Julian

**Comment by ChongJenniferZhang** [comment]
Hi Julian,

I checked and re-downloaded categs.txt file and it works fine now. Thanks for your suggestion. 

Best,
Jennifer

**Comment by julianhess** [comment]
Great! Let me know if you have any other issues.
