### ISSUE TITLE
MutsigCV

### ISSUE THREAD

**Issue by Gtt19920502** [broadinstitute/getzlab-PCAWG-MutSig2CV_NC#4]
Hello,

I use MutSigCV analyzed my mutation data. It shows some error. I think maybe something is wrong with my input file. Could you please tell me how to revise it? The error is:

Error using gp_MutSigCV>MutSig_runCV (line 850)
not enough mutations to analyze

Error in gp_MutSigCV (line 194)
 MutSigCV
  v1.3

  (c) Mike Lawrence and Gaddy Getz
  Broad Institute of MIT and Harvard
======================================

MutSigCV: PREPROCESS
--------------------
Loading mutation_file...
Loading coverage file...
Processing mutation "effect"...
WARNING:  2/21453 mutations could not be mapped to effect using mutation_type_dictionary_file:

             : [2]
    ----TOTAL: [2]
          They will be removed from the analysis.
Processing mutation "categ"...
NOTE:  unable to perform category discovery, because no chr_files available.Will use two categories: missense and null+indel.
Collapsing coverage...
Writing preprocessed files.
MutSig_preprocess finished.

Thanks.
The following one is input file:
Hugo_Symbol	Tumor_Sample_Barcode	Variant_Classification	Chromosome	Start_position	Reference_Allele	Tumor_Seq_Allele1	Tumor_Seq_Allele2
A1CF	LM-BN-1	3'UTR	10	52563029	GT	G	G
A1CF	LM-BN-4	3'UTR	10	52563029	GT	G	G
A1CF	LM-BN-5	3'UTR	10	52566432	CT	C	C
A2M	LM-BN-1	Intron	12	9220823	G	GA	GA
A2M	LM-BN-4	Intron	12	9220823	G	GA	GA
A2ML1	LM-BN-1	3'UTR	12	9028242	T	C	C
A2ML1	LM-BN-1	3'UTR	12	9028264	G	A	A
AAAS	LM-BN-1	Missense_Mutation	12	53715218	G	A	A
AACS	LM-BN-1	5'UTR	12	125586335	TG	CA	CA
AACS	LM-BN-2	5'UTR	12	125607905	A	G	G
AACS	LM-BN-2	5'UTR	12	125607960	C	G	G
AACS	LM-BN-3	5'UTR	12	125586308	CTT	C	C
AACS	LM-BN-3	5'UTR	12	125586308	CTT	CTTT	CTTT
AACS	LM-BN-4	5'UTR	12	125586308	CT	C	C
AACS	LM-BN-4	5'UTR	12	125586308	CT	CTT	CTT
AACS	LM-BN-1	5'UTR	12	125586359	G	C	C

**Comment by hurrialice** [comment]
Hi,

Have you downloaded "all.fwb" and "all.fwi" from the bucket `gs://getzlab-pcawg-mutsig2cv_nc/` as mentioned [here](https://github.com/broadinstitute/getzlab-PCAWG-MutSig2CV_NC/blob/master/ref/README.md)?

**Comment by julianhess** [comment]
Hi @Gtt19920502,

It seems that you're trying to run the original 2010 MutSigCV algorithm. This repo contains the release of MutSig2CV specifically for noncoding element analysis.

Rather than trying to get MutSigCV to work, it will be much easier to use the latest release of MutSig2CV for coding elements, which supersedes the original MutSigCV.

Please download that here: http://software.broadinstitute.org/cancer/cga/sites/default/files/data/tools/mutsig/MutSig2CV.tar.gz

Note that it is a large download (~3 GB), since it includes all necessary reference files.  Installation instructions are provided in the README.txt file.  In addition to the MutSig executable, you will also need the MATLAB runtime environment, available here: http://www.mathworks.com/supportfiles/MCR_Runtime/R2013a/MCR_R2013a_glnxa64_installer.zip

**Comment by Gtt19920502** [comment]
> Hi @Gtt19920502,
> 
> It seems that you're trying to run the original 2010 MutSigCV algorithm. This repo contains the release of MutSig2CV specifically for noncoding element analysis.
> 
> Rather than trying to get MutSigCV to work, it will be much easier to use the latest release of MutSig2CV for coding elements, which supersedes the original MutSigCV.
> 
> Please download that here: http://software.broadinstitute.org/cancer/cga/sites/default/files/data/tools/mutsig/MutSig2CV.tar.gz
> 
> Note that it is a large download (~3 GB), since it includes all necessary reference files. Installation instructions are provided in the README.txt file. In addition to the MutSig executable, you will also need the MATLAB runtime environment, available here: http://www.mathworks.com/supportfiles/MCR_Runtime/R2013a/MCR_R2013a_glnxa64_installer.zip

Hi Julianhess,

Thank you very much for your reply and informations. I think maybe something wrong with my input file. I'll try it according your suggestion. Thank you very much.

**Comment by Gtt19920502** [comment]
> Hi,
> 
> Have you downloaded "all.fwb" and "all.fwi" from the bucket `gs://getzlab-pcawg-mutsig2cv_nc/` as mentioned [here](https://github.com/broadinstitute/getzlab-PCAWG-MutSig2CV_NC/blob/master/ref/README.md)?

Hello,

Thank you very much for your reply. I used the MutSigCV 1.3 software. I'm not whether my input file is wrong? Thank you very much. The following one is my input. Could you please help me th check it whether it's right or not? Thank you very much.
Hugo_Symbol	Tumor_Sample_Barcode	Variant_Classification	Chromosome	Start_position	Reference_Allele	Tumor_Seq_Allele1	Tumor_Seq_Allele2
A1CF	LM-BN-1	3'UTR	10	52563029	GT	G	G
A1CF	LM-BN-4	3'UTR	10	52563029	GT	G	G
A1CF	LM-BN-5	3'UTR	10	52566432	CT	C	C
A2M	LM-BN-1	Intron	12	9220823	G	GA	GA
A2M	LM-BN-4	Intron	12	9220823	G	GA	GA
A2ML1	LM-BN-1	3'UTR	12	9028242	T	C	C
A2ML1	LM-BN-1	3'UTR	12	9028264	G	A	A
AAAS	LM-BN-1	Missense_Mutation	12	53715218	G	A	A
AACS	LM-BN-1	5'UTR	12	125586335	TG	CA	CA
AACS	LM-BN-2	5'UTR	12	125607905	A	G	G
AACS	LM-BN-2	5'UTR	12	125607960	C	G	G
AACS	LM-BN-3	5'UTR	12	125586308	CTT	C	C
AACS	LM-BN-3	5'UTR	12	125586308	CTT	CTTT	CTTT
AACS	LM-BN-4	5'UTR	12	125586308	CT	C	C
AACS	LM-BN-4	5'UTR	12	125586308	CT	CTT	CTT
AACS	LM-BN-1	5'UTR	12	125586359	G	C	C
AADACL3	LM-BN-1	3'UTR	1	12787881	G	A	A
AADACL3	LM-BN-1	Missense_Mutation	1	12785945	A	T	T
AADAT	LM-BN-3	3'UTR	4	170981506	TAAAAGTAGA	T	T
AAED1	LM-BN-4	3'UTR	9	99402375	C	CA	CA
AAED1	LM-BN-1	Missense_Mutation	9	99413690	C	T	T
AAGAB	LM-BN-4	3'UTR	15	67493515	CT	C	C
AAGAB	LM-BN-5	3'UTR	15	67493515	CT	C	C
AAGAB	LM-BN-5	3'UTR	15	67493515	CT	CTT	CTT
AAK1	LM-BN-1	3'UTR	2	69688727	A	AT	AT
AAK1	LM-BN-2	3'UTR	2	69709361	G	A	A
AAK1	LM-BN-3	3'UTR	2	69688631	CA	C	C
AAK1	LM-BN-3	3'UTR	2	69688631	CA	CAA	CAA
AAK1	LM-BN-3	3'UTR	2	69702102	T	TCCCCCCC	TCCCCCCC

**Comment by Gtt19920502** [comment]
Yeah, It shows closed. I'll send the input now. Could you please tell me
can you check it? Thank you very much.
Hugo_Symbol Tumor_Sample_Barcode Variant_Classification Chromosome
Start_position Reference_Allele Tumor_Seq_Allele1 Tumor_Seq_Allele2
A1CF LM-BN-1 3'UTR 10 52563029 GT G G
A1CF LM-BN-4 3'UTR 10 52563029 GT G G
A1CF LM-BN-5 3'UTR 10 52566432 CT C C
A2M LM-BN-1 Intron 12 9220823 G GA GA
A2M LM-BN-4 Intron 12 9220823 G GA GA
A2ML1 LM-BN-1 3'UTR 12 9028242 T C C
A2ML1 LM-BN-1 3'UTR 12 9028264 G A A
AAAS LM-BN-1 Missense_Mutation 12 53715218 G A A
AACS LM-BN-1 5'UTR 12 125586335 TG CA CA
AACS LM-BN-2 5'UTR 12 125607905 A G G
AACS LM-BN-2 5'UTR 12 125607960 C G G
AACS LM-BN-3 5'UTR 12 125586308 CTT C C
AACS LM-BN-3 5'UTR 12 125586308 CTT CTTT CTTT
AACS LM-BN-4 5'UTR 12 125586308 CT C C
AACS LM-BN-4 5'UTR 12 125586308 CT CTT CTT
AACS LM-BN-1 5'UTR 12 125586359 G C C

Thanks

julianhess <notifications@github.com> 于2020年7月13日周一 下午7:02写道：

**Comment by hurrialice** [comment]
Hi @Gtt19920502 ,

It seems that you are still using MutSigCV. If so, please use **MutSig2CV** downloaded as @julianhess described. MutSigCV on GenePattern is not up-to-date and will not be further supported.

Your input file seems okay. If you are still encountering problems with **MutSIg2CV**, please attach the log with your reply here.

Thanks!

**Comment by Gtt19920502** [comment]
Hello Qing,

Thank you very much for your reply. I will try to do it using MutSig2CV.

Thanks!

qing zhang <notifications@github.com> 于2020年7月17日周五 上午9:01写道：

**Comment by Gtt19920502** [comment]
Hello Qing,

The following one is the result of running MutSig2CV. It also shows error.
Could you please tell me how to revise:
[image: image.png]

Thanks

qing zhang <notifications@github.com> 于2020年7月17日周五 上午9:01写道：

**Comment by Gtt19920502** [comment]
Hello Qing,

The following one is the result of running MutSig2CV. It also shows error.
Could you please tell me how to revise:
-/MntsigGV/mutsig2cv$。/Mutsig2CV II-MAF, mat outputWarning: latest version
of matlab app-defaults file not foundContact your system administrator to
have this file installedMUTSIG VERSION E
2cv3.11
LOADING DATA
Processing target list
oading mutations
Mutation file contains multiple columns for newbase info
Tumor_seq Allele
newbase
ill use newbase
Mutation file is missing a column named one of the following:
classification
Variant_Type
Error using Mutsig_2CV_v3_11_core(line 169)
Mutation file missing classification column
Error in Mutsig-_2cV_v3_11 wrapper(line 50)

Thanks

qing zhang <notifications@github.com> 于2020年7月17日周五 上午9:01写道：

**Comment by hurrialice** [comment]
HI @Gtt19920502 

The error message is self-explanatory.  Consider revising your table by changing column names, one example table would be 

```
$ head /demo-mount/M2_refs/MC3.maf 
chr	pos	gene	ref_allele	newbase	type	classification	patient
1	13308		T	G	IGR	SNP	11D-09
1	13372		G	T	IGR	SNP	11D-08
1	13501		G	A	IGR	SNP	11D-08
1	13515		C	A	IGR	SNP	01D-08
1	13516		C	A	IGR	SNP	01D-08
1	13516		C	A	IGR	SNP	12D-09
```

MutSig2CV only expects 1 column of alt allele.

**Comment by julianhess** [comment]
You need to add a field for the "Variant_Type," which is described here: https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/

**Comment by Gtt19920502** [comment]
Hi Julian,

Thank you very much for your reply. I get it. I'll add the "Variant_Type"
and try it again.

Thanks

julianhess <notifications@github.com> 于2020年7月18日周六 下午8:10写道：

**Comment by Gtt19920502** [comment]
Hello Qing,

Thank you very much for your reply. I get it. I'll revise it and try it
again.

Thanks

qing zhang <notifications@github.com> 于2020年7月18日周六 下午8:06写道：
